#Definições de tela
TITULO = 'Pygame'
LARGURA = 1400
ALTURA = 700

#Definições de jogo
TILE_SIZE = 70
FPS = 60

#Definições de arquivos
SPRITESHEET_ENEMY = 'Enemy.png'
SPRITESHEE_KEYS = 'Keys.png'
HEART_PNG = 'Heart.png'
SPRITESHEET_HERO = 'hero_sprites.png'

#Definições do Player
PLAYER_ACC = 0.5
PLAYER_FRICTION = -0.12
GRAVIDADE = 0.8
PLAYER_JUMP = 19
PLAYER_DAMAGE = 30

#Mapa de Tiles
CHAO = 1
TERRA = 2
CEU = 3
BASE = 4
BASE_E = 5
BASE_D = 6

MAP = [
    [CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU],
    [CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU],
    [CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU],
    [CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	BASE_E,	BASE,	BASE,	BASE,	BASE,	BASE,	BASE,   BASE,   BASE,   BASE],
    [CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU],
    [BASE,	BASE,	BASE,	BASE,	BASE,	BASE,	BASE,	BASE_D,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU],
    [CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU],
    [CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU,	CEU],
    [CHAO,	CHAO,	CHAO,	CHAO,	CHAO,	CHAO,	CHAO,	CHAO,	CHAO,	CHAO,	CHAO,	CHAO,	CHAO,	CHAO,	CHAO,	CHAO,	CHAO,	CHAO,	CHAO,	CHAO],
    [TERRA,	TERRA,	TERRA,	TERRA,	TERRA,	TERRA,	TERRA,	TERRA,	TERRA,	TERRA,	TERRA,	TERRA,	TERRA,	TERRA,	TERRA,	TERRA,	TERRA,	TERRA,	TERRA,	TERRA],
  
]

#Tela
TITLE = 'Bem vindo'
FONT_NAME = 'Courier'

#Cores para serem utilizadas
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (106, 159, 181)
YELLOW = (255, 255, 0)
GREEN2 = (102,255,178)